### ISSUE TITLE
Improvements to commands/new commands (see comment)

### ISSUE THREAD

**Issue by jennyyu73** [alexmcq99/discord-bot#6]
-play should be able to search by keywords instead of having to be a youtube link
-skip
-playall to play all downloaded songs on the server (so don't need to wait for songs to download)
-loop the queue 
-remove specific song from queue

**Comment by amcquilkin** [comment]
-skip, -playall, -loop, and -remove were all added.
I also added -showqueue to show the current song, current queue, and if the queue is looping or not.

**Comment by amcquilkin** [comment]
Added keyword search for -play and ability to search multiple urls at once, separated by spaces
